### ISSUE TITLE
Use of template literal ` in vision() statement

### ISSUE THREAD

**Issue by shashankbhosagi** [AssembleProgramming/AssembleScript#28]
### Use Case

To introduce use of template literals in vision statement to make vision more userful. 

### Proposed Solution

Now in vision() in AssembleScript we can only use double quotes.
```javascript
vision("Avengers Assemble!!!!!!!!!!");
```
After using template literals we can use template literal in vision as follows.
```javascript
vision(`Avengers Assemble!!!`);
```

### Benefits

Main benefit of using a template literal is that you can use value of variables using $ in general Javascript

### Possible Implementation

Possible implementation are'`Avengers Assemble ${var1}`' but one issue here is, that we use $ for comment in template literalls. So we can use @ or any other symbols..

---

**Comment by SahilK-027** [comment]
Assign it to me 👍🏻
