### ISSUE TITLE
Add Documentation for new Team syntax in README.md

### ISSUE THREAD

**Issue by shashankbhosagi** [AssembleProgramming/AssembleScript#29]
### Use Case

In the documentation update the documentation for the team

### Proposed Solution

- Previously team syntax was 
```javascript
team avengers(4) = {"ironman", "thor", "spiderman", "captain america"};
vision(avengers[0]); $output -> ironman
```
- New team syntax is 
```javascript
team avengers[4] = {"ironman", "thor", "spiderman", "captain america"};
vision(avengers[0]); $output -> ironman
```
- Added `[ ]` for more intuitions
---

**Comment by Shahzaib-Iqbal-1057** [comment]
We just have to change the array syntax from () to []? (Sorry first-time contributor here)

**Comment by SahilK-027** [comment]
Actually, this change have been made...We are about to update the documentation.
